version: '3'
services:
  staging_web:
    image: segsoft/fluxnode:latest
    ports:
      - 6220:80
    volumes:
      - bankly_staging_web_new:/var/www:cached
    environment:
      - APP_ENV=staging
      - GIT_OAUTH2_TOKEN=${GIT_OAUTH2_TOKEN}
      - REPOSITORY_URL=gitlab.com/bankly/web.git
      - PORT=6220
      - APP_NAME=bankly-web-new
      - GIT_BRANCH=staging
    container_name: bankly_staging_web_new

volumes:
  bankly_staging_web_new:
