/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    'consular-services': ConsularService;
    'news-articles': NewsArticle;
    'staff-members': StaffMember;
    media: Media;
    users: User;
    'user-roles': UserRole;
    forms: Form;
    'form-submissions': FormSubmission;
  };
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
}
export interface Page {
  id: string;
  title: string;
  slug?: string;
  layout: (
    | {
        eyebrow?: string;
        heading: string;
        headingAccent?: string;
        subheading?: string;
        showSearch?: boolean;
        searchPlaceholder?: string;
        quickLinks?: {
          label: string;
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            newTab?: boolean;
          };
          id?: string;
        }[];
        slides: {
          media: string | Media;
          poster?: string | Media;
          caption?: string;
          heading?: string;
          subheading?: string;
          cta?: {
            enabled?: boolean;
            value?: {
              type?: 'reference' | 'custom' | 'current-document';
              reference?: {
                value?:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | ConsularService;
                      relationTo: 'consular-services';
                    }
                  | {
                      value: string | NewsArticle;
                      relationTo: 'news-articles';
                    };
              };
              url?: string;
              section?: string;
              label?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
          };
          id?: string;
        }[];
        autoplayInterval?: number;
        id?: string;
        blockName?: string;
        blockType: 'hero-slider';
      }
    | {
        eyebrow?: string;
        heading: string;
        lead?: string;
        actions?: {
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        showBreadcrumbs?: boolean;
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'page-hero';
      }
    | {
        severity: 'notice' | 'warning' | 'emergency';
        badge?: string;
        message: string;
        link?: {
          enabled?: boolean;
          value?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
          };
        };
        dismissible?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'alert-bar';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        groups: {
          title: string;
          icon?: string | Media;
          populateBy: 'category' | 'selection' | 'manual';
          category?: 'immigration' | 'consular';
          services?: string[] | ConsularService[];
          links?: {
            label: string;
            action?: {
              type?: 'reference' | 'custom' | 'current-document';
              reference?: {
                value?:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | ConsularService;
                      relationTo: 'consular-services';
                    }
                  | {
                      value: string | NewsArticle;
                      relationTo: 'news-articles';
                    };
              };
              url?: string;
              section?: string;
              newTab?: boolean;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        populatedData?: {};
        populatable?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'service-grid';
      }
    | {
        staffMember?: string | StaffMember;
        eyebrow?: string;
        heading: string;
        message: {
          [k: string]: unknown;
        }[];
        showSignature?: boolean;
        showSocialLinks?: boolean;
        bioLink?: {
          enabled?: boolean;
          value?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
          };
        };
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'high-commissioner-section';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        variant?: 'glance' | 'impact';
        stats: {
          value: string;
          label: string;
          id?: string;
        }[];
        quotes?: {
          quote: string;
          attribution?: string;
          id?: string;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'stats-section';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        videos: {
          video: string | Media;
          poster?: string | Media;
          tag?: string;
          title: string;
          description?: string;
          id?: string;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'video-gallery';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        limit: number;
        category?:
          | 'announcements'
          | 'consular-updates'
          | 'immigration'
          | 'high-commission-activities'
          | 'nigeria-australia-relations'
          | 'community'
          | 'events';
        showViewAll?: boolean;
        viewAllLabel?: string;
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        populatedData?: {};
        populatable?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'news-grid';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        highlightHighCommissioner?: boolean;
        columns?: '2' | '3' | '4';
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        populatedData?: {};
        populatable?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'staff-grid';
      }
    | {
        content: {
          [k: string]: unknown;
        }[];
        width?: 'narrow' | 'default' | 'wide';
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'rich-text';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        form: string | Form;
        layout?: 'with-info' | 'banner';
        info?: {
          [k: string]: unknown;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'contact-form';
      }
    | {
        arrangement?: 'media-first' | 'content-first';
        emphasis?: 'moderate' | 'media' | 'content';
        content: {
          [k: string]: unknown;
        }[];
        media?: {
          ref?: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        actions?: {
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        backgroundMedia?: string | Media;
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'media-content-block';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        variant?: 'cards' | 'tasks' | 'plain';
        columns?: '2' | '3' | '4';
        items: {
          icon?: string | Media;
          title: string;
          description?: string;
          action?: {
            enabled?: boolean;
            value?: {
              type?: 'reference' | 'custom' | 'current-document';
              reference?: {
                value?:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | ConsularService;
                      relationTo: 'consular-services';
                    }
                  | {
                      value: string | NewsArticle;
                      relationTo: 'news-articles';
                    };
              };
              url?: string;
              section?: string;
              label?: string;
              newTab?: boolean;
            };
          };
          id?: string;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'item-grid-block';
      }
    | {
        size?: 'default' | 'full-width';
        media: {
          ref: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        caption?: string;
        centered?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'media-block';
      }
    | {
        compact?: boolean;
        columns: {
          sizeRatio: string;
          entries?: (
            | {
                sizeRatio: string;
                medias: {
                  gridMedia?: {
                    sizeRatio: string;
                    media?: string | Media;
                  };
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'row';
              }
            | {
                gridMedia?: {
                  sizeRatio: string;
                  media?: string | Media;
                };
                id?: string;
                blockName?: string;
                blockType: 'media';
              }
          )[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-grid-block';
      }
    | {
        cards: {
          title?: string;
          content?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'expandable-cards-block';
      }
    | {
        title?: {
          [k: string]: unknown;
        }[];
        assets?: {
          asset: string | Media;
          name?: string;
          boxed?: boolean;
          id?: string;
        }[];
        columns?: string;
        mediaAspectRatio?: string;
        hideDownloadButton?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'downloadable-assets-block';
      }
    | {
        actions?: {
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'action-group-block';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface ConsularService {
  id: string;
  title: string;
  slug?: string;
  category: 'immigration' | 'consular';
  group?: string;
  order?: number;
  shortDescription: string;
  lead?: string;
  icon?: string | Media;
  actions?: {
    action?: {
      type?: 'reference' | 'custom' | 'current-document';
      reference?: {
        value?:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | ConsularService;
              relationTo: 'consular-services';
            }
          | {
              value: string | NewsArticle;
              relationTo: 'news-articles';
            };
      };
      url?: string;
      section?: string;
      label?: string;
      newTab?: boolean;
      showArrow?: boolean;
      params?: {
        key: string;
        value: string;
        id?: string;
      }[];
      decoration?: {
        variant?: 'text' | 'contained' | 'outlined';
        color?: 'inherit' | 'primary' | 'secondary' | 'white';
      };
    };
    id?: string;
  }[];
  overview?: {
    [k: string]: unknown;
  }[];
  steps?: {
    title: string;
    description?: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
  processingTime?: string;
  fees?: {
    item: string;
    amount: string;
    paymentMethod?: string;
    note?: string;
    id?: string;
  }[];
  requirements?: {
    heading?: string;
    items: {
      text: string;
      note?: string;
      id?: string;
    }[];
    id?: string;
  }[];
  downloads?: {
    label: string;
    file: string | Media;
    id?: string;
  }[];
  relatedServices?: string[] | ConsularService[];
  extraSections?: (
    | {
        content: {
          [k: string]: unknown;
        }[];
        width?: 'narrow' | 'default' | 'wide';
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'rich-text';
      }
    | {
        severity: 'notice' | 'warning' | 'emergency';
        badge?: string;
        message: string;
        link?: {
          enabled?: boolean;
          value?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
          };
        };
        dismissible?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'alert-bar';
      }
    | {
        arrangement?: 'media-first' | 'content-first';
        emphasis?: 'moderate' | 'media' | 'content';
        content: {
          [k: string]: unknown;
        }[];
        media?: {
          ref?: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        actions?: {
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        backgroundMedia?: string | Media;
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'media-content-block';
      }
    | {
        eyebrow?: string;
        heading?: string;
        intro?: string;
        variant?: 'cards' | 'tasks' | 'plain';
        columns?: '2' | '3' | '4';
        items: {
          icon?: string | Media;
          title: string;
          description?: string;
          action?: {
            enabled?: boolean;
            value?: {
              type?: 'reference' | 'custom' | 'current-document';
              reference?: {
                value?:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | ConsularService;
                      relationTo: 'consular-services';
                    }
                  | {
                      value: string | NewsArticle;
                      relationTo: 'news-articles';
                    };
              };
              url?: string;
              section?: string;
              label?: string;
              newTab?: boolean;
            };
          };
          id?: string;
        }[];
        section?: {
          theme?: 'paper' | 'cream' | 'deep' | 'gold';
          spacing?: 'default' | 'compact' | 'spacious' | 'none';
        };
        id?: string;
        blockName?: string;
        blockType: 'item-grid-block';
      }
    | {
        cards: {
          title?: string;
          content?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'expandable-cards-block';
      }
    | {
        title?: {
          [k: string]: unknown;
        }[];
        assets?: {
          asset: string | Media;
          name?: string;
          boxed?: boolean;
          id?: string;
        }[];
        columns?: string;
        mediaAspectRatio?: string;
        hideDownloadButton?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'downloadable-assets-block';
      }
    | {
        actions?: {
          action?: {
            type?: 'reference' | 'custom' | 'current-document';
            reference?: {
              value?:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | ConsularService;
                    relationTo: 'consular-services';
                  }
                | {
                    value: string | NewsArticle;
                    relationTo: 'news-articles';
                  };
            };
            url?: string;
            section?: string;
            label?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'action-group-block';
      }
    | {
        size?: 'default' | 'full-width';
        media: {
          ref: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        caption?: string;
        centered?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'media-block';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  alt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
export interface NewsArticle {
  id: string;
  title: string;
  slug?: string;
  publishedDate: string;
  category:
    | 'announcements'
    | 'consular-updates'
    | 'immigration'
    | 'high-commission-activities'
    | 'nigeria-australia-relations'
    | 'community'
    | 'events';
  author?: string;
  tags?: string;
  excerpt: string;
  coverImage?: string | Media;
  body: {
    [k: string]: unknown;
  }[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface StaffMember {
  id: string;
  name: string;
  title: string;
  photo?: string | Media;
  bio?: {
    [k: string]: unknown;
  }[];
  socialLinks?: {
    platform:
      | 'x'
      | 'facebook'
      | 'instagram'
      | 'linkedin'
      | 'youtube'
      | 'tiktok'
      | 'whatsapp';
    url: string;
    handle?: string;
    id?: string;
  }[];
  order?: number;
  isHighCommissioner?: boolean;
  createdAt: string;
  updatedAt: string;
}
export interface Form {
  id: string;
  title: string;
  fields?: (
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'text';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'textarea';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        options?: {
          label: string;
          value: string;
          id?: string;
        }[];
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'select';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'email';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'state';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'country';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'number';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        defaultValue?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'checkbox';
      }
    | {
        message?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'message';
      }
  )[];
  submitButtonLabel?: string;
  confirmationType?: 'message' | 'redirect';
  confirmationMessage: {
    [k: string]: unknown;
  }[];
  redirect?: {
    url: string;
  };
  emails?: {
    emailTo?: string;
    cc?: string;
    bcc?: string;
    replyTo?: string;
    emailFrom?: string;
    subject: string;
    message?: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
  slug?: string;
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  name?: string;
  role?: string | UserRole;
  photo?: string | Media;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface UserRole {
  id: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?: {
    field: string;
    value: string;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Header {
  id: string;
  items: {
    label: string;
    type: 'link' | 'dropdown';
    action?: {
      type?: 'reference' | 'custom' | 'current-document';
      reference?: {
        value?:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | ConsularService;
              relationTo: 'consular-services';
            }
          | {
              value: string | NewsArticle;
              relationTo: 'news-articles';
            };
      };
      url?: string;
      section?: string;
      newTab?: boolean;
    };
    highlight?: boolean;
    groups?: {
      label?: string;
      links: {
        label: string;
        action?: {
          type?: 'reference' | 'custom' | 'current-document';
          reference?: {
            value?:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | ConsularService;
                  relationTo: 'consular-services';
                }
              | {
                  value: string | NewsArticle;
                  relationTo: 'news-articles';
                };
          };
          url?: string;
          section?: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
      id?: string;
    }[];
    id?: string;
  }[];
}
export interface Footer {
  id: string;
  columns?: {
    title: string;
    links: {
      label: string;
      action?: {
        type?: 'reference' | 'custom' | 'current-document';
        reference?: {
          value?:
            | {
                value: string | Page;
                relationTo: 'pages';
              }
            | {
                value: string | ConsularService;
                relationTo: 'consular-services';
              }
            | {
                value: string | NewsArticle;
                relationTo: 'news-articles';
              };
        };
        url?: string;
        section?: string;
        newTab?: boolean;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  contact?: {
    organisationName?: string;
    address?: string;
    phone?: string;
    email?: string;
    hours?: string;
  };
  socialLinks?: {
    platform:
      | 'x'
      | 'facebook'
      | 'instagram'
      | 'linkedin'
      | 'youtube'
      | 'tiktok'
      | 'whatsapp';
    url: string;
    handle?: string;
    id?: string;
  }[];
  ministry?: {
    label?: string;
    logo?: string | Media;
    url?: string;
  };
  copyright?: string;
  bottomLinks?: {
    label: string;
    action?: {
      type?: 'reference' | 'custom' | 'current-document';
      reference?: {
        value?:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | ConsularService;
              relationTo: 'consular-services';
            }
          | {
              value: string | NewsArticle;
              relationTo: 'news-articles';
            };
      };
      url?: string;
      section?: string;
      newTab?: boolean;
    };
    id?: string;
  }[];
}
export interface SiteSetting {
  id: string;
  siteName: string;
  siteTagline?: string;
  emblem?: string | Media;
  logo?: string | Media;
  ogImage?: string | Media;
  alertBar?: {
    enabled?: boolean;
    severity?: 'notice' | 'warning' | 'emergency';
    badge?: string;
    message?: string;
    link?: {
      enabled?: boolean;
      value?: {
        type?: 'reference' | 'custom' | 'current-document';
        reference?: {
          value?:
            | {
                value: string | Page;
                relationTo: 'pages';
              }
            | {
                value: string | ConsularService;
                relationTo: 'consular-services';
              }
            | {
                value: string | NewsArticle;
                relationTo: 'news-articles';
              };
        };
        url?: string;
        section?: string;
        label?: string;
        newTab?: boolean;
      };
    };
    dismissible?: boolean;
  };
  seo?: {
    titleTemplate?: string;
    defaultDescription?: string;
  };
}
