/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    headers: Header;
    footers: Footer;
    'reusable-content': ReusableContent;
    users: User;
    'user-roles': UserRole;
    media: Media;
    testimonials: Testimonial;
    'case-studies': CaseStudy;
    agents: Agent;
    openings: Opening;
    'blog-posts': BlogPost;
    blogPostCategories: BlogPostCategory;
    'help-topics': HelpTopic;
    'help-articles': HelpArticle;
    'team-members': TeamMember;
    'press-posts': PressPost;
    forms: Form;
    'form-submissions': FormSubmission;
  };
  globals: {};
}
export interface Page {
  id: string;
  title?: string;
  layout?: {
    header: string | Header;
    footer: string | Footer;
  };
  hero?: {
    disabled?: boolean;
    block: (
      | {
          showBreadcrumb?: boolean;
          title: {
            [k: string]: unknown;
          }[];
          centered?: boolean;
          action?: {
            enabled?: boolean;
            value?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
          };
          expanded?: boolean;
          hero?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'title-block';
          bannerMedia: string | Media;
        }
      | {
          arrangement?: 'media-first' | 'content-first';
          emphasis?: 'moderate' | 'media' | 'content';
          content?: {
            [k: string]: unknown;
          }[];
          showLicenceSnippet?: boolean;
          showInvestModal?: boolean;
          showDownTimeModal?: boolean;
          media: {
            ref: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          bannerMedia: string | Media;
          mediaSticksToBottom?: boolean;
          actions?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          hero?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'media-content-block';
        }
    )[];
    spacing?: {
      top?: boolean;
      bottom?: boolean;
    };
    background?: {
      color?: string;
      pattern?:
        | 'none'
        | 'discs'
        | 'flat-discs'
        | 'left-positioned-logo'
        | 'right-positioned-logo'
        | 'spiral'
        | 'spiral-cluster';
      media?: {
        enabled?: boolean;
        value?: string | Media;
      };
    };
    overlapsHeader?: boolean;
  };
  sections: {
    boxed?: boolean;
    blocks?: (
      | {
          showBreadcrumb?: boolean;
          title: {
            [k: string]: unknown;
          }[];
          centered?: boolean;
          action?: {
            enabled?: boolean;
            value?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
          };
          expanded?: boolean;
          hero?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'title-block';
        }
      | {
          arrangement?: 'media-first' | 'content-first';
          emphasis?: 'moderate' | 'media' | 'content';
          content?: {
            [k: string]: unknown;
          }[];
          showLicenceSnippet?: boolean;
          showInvestModal?: boolean;
          showDownTimeModal?: boolean;
          media: {
            ref: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          bannerMedia: string | Media;
          mediaSticksToBottom?: boolean;
          actions?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          hero?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'media-content-block';
        }
      | {
          size?: 'default' | 'full-width';
          media: {
            ref: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          bannerMedia: string | Media;
          caption?: string;
          centered?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'media-block';
        }
      | {
          reference: string | ReusableContent;
          id?: string;
          blockName?: string;
          blockType: 'reusable-content-block';
        }
      | {
          tabs?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'tabs-block';
        }
      | {
          type?: 'default' | 'collapsible' | 'interactive';
          arrangement?: 'media-first' | 'content-first';
          features?: {
            content?: {
              [k: string]: unknown;
            }[];
            numbered?: boolean;
            icon?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            action?: {
              enabled?: boolean;
              value?: {
                type?:
                  | 'reference'
                  | 'custom'
                  | 'current-document'
                  | 'app-store'
                  | 'google-play-store';
                reference?: {
                  value?: {
                    value: string | Page;
                    relationTo: 'pages';
                  };
                };
                section?: string;
                label?: string;
                url?: string;
                newTab?: boolean;
                showArrow?: boolean;
                params?: {
                  key: string;
                  value: string;
                  id?: string;
                }[];
                decoration?: {
                  variant?: 'text' | 'contained' | 'outlined';
                  color?: 'inherit' | 'primary' | 'secondary' | 'white';
                };
              };
            };
            id?: string;
          }[];
          collapsibleFeatures?: {
            title?: string;
            content?: {
              [k: string]: unknown;
            }[];
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            id?: string;
          }[];
          interactiveFeatures?: {
            content?: {
              [k: string]: unknown;
            }[];
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            id?: string;
          }[];
          title?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          mediaSticksToBottom?: boolean;
          grid?: boolean;
          actions?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'features-block';
        }
      | {
          type: 'media' | 'agent';
          showArrows?: boolean;
          medias: {
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            label?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
          agents: string[] | Agent[];
          id?: string;
          blockName?: string;
          blockType: 'slider-block';
        }
      | {
          items?: {
            icon?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            content?: {
              [k: string]: unknown;
            }[];
            centered?: boolean;
            action?: {
              enabled?: boolean;
              value?: {
                type?:
                  | 'reference'
                  | 'custom'
                  | 'current-document'
                  | 'app-store'
                  | 'google-play-store';
                reference?: {
                  value?: {
                    value: string | Page;
                    relationTo: 'pages';
                  };
                };
                section?: string;
                url?: string;
                newTab?: boolean;
                showArrow?: boolean;
                params?: {
                  key: string;
                  value: string;
                  id?: string;
                }[];
                decoration?: {
                  variant?: 'text' | 'contained' | 'outlined';
                  color?: 'inherit' | 'primary' | 'secondary' | 'white';
                };
              };
            };
            id?: string;
          }[];
          columns?: string;
          mediaAspectRatio?: string;
          id?: string;
          blockName?: string;
          blockType: 'item-grid-block';
        }
      | {
          emphasis?: 'moderate' | 'content1' | 'content2';
          content1?: {
            [k: string]: unknown;
          }[];
          content2?: {
            [k: string]: unknown;
          }[];
          actions?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'content-content-block';
        }
      | {
          conditions?: {
            key: string;
            value: string;
            id?: string;
          }[];
          child: (
            | {
                showBreadcrumb?: boolean;
                title: {
                  [k: string]: unknown;
                }[];
                centered?: boolean;
                action?: {
                  enabled?: boolean;
                  value?: {
                    type?:
                      | 'reference'
                      | 'custom'
                      | 'current-document'
                      | 'app-store'
                      | 'google-play-store';
                    reference?: {
                      value?: {
                        value: string | Page;
                        relationTo: 'pages';
                      };
                    };
                    section?: string;
                    label?: string;
                    url?: string;
                    newTab?: boolean;
                    showArrow?: boolean;
                    params?: {
                      key: string;
                      value: string;
                      id?: string;
                    }[];
                    decoration?: {
                      variant?: 'text' | 'contained' | 'outlined';
                      color?: 'inherit' | 'primary' | 'secondary' | 'white';
                    };
                  };
                };
                expanded?: boolean;
                hero?: boolean;
                id?: string;
                blockName?: string;
                blockType: 'title-block';
              }
            | {
                type?: 'default' | 'collapsible' | 'interactive';
                arrangement?: 'media-first' | 'content-first';
                features?: {
                  content?: {
                    [k: string]: unknown;
                  }[];
                  numbered?: boolean;
                  icon?: {
                    ref?: string | Media;
                    maxHeight?: string;
                    aspectRatio?: string;
                    autoplay?: boolean;
                  };
                  action?: {
                    enabled?: boolean;
                    value?: {
                      type?:
                        | 'reference'
                        | 'custom'
                        | 'current-document'
                        | 'app-store'
                        | 'google-play-store';
                      reference?: {
                        value?: {
                          value: string | Page;
                          relationTo: 'pages';
                        };
                      };
                      section?: string;
                      label?: string;
                      url?: string;
                      newTab?: boolean;
                      showArrow?: boolean;
                      params?: {
                        key: string;
                        value: string;
                        id?: string;
                      }[];
                      decoration?: {
                        variant?: 'text' | 'contained' | 'outlined';
                        color?: 'inherit' | 'primary' | 'secondary' | 'white';
                      };
                    };
                  };
                  id?: string;
                }[];
                collapsibleFeatures?: {
                  title?: string;
                  content?: {
                    [k: string]: unknown;
                  }[];
                  media?: {
                    ref?: string | Media;
                    maxHeight?: string;
                    aspectRatio?: string;
                    autoplay?: boolean;
                  };
                  id?: string;
                }[];
                interactiveFeatures?: {
                  content?: {
                    [k: string]: unknown;
                  }[];
                  media?: {
                    ref?: string | Media;
                    maxHeight?: string;
                    aspectRatio?: string;
                    autoplay?: boolean;
                  };
                  id?: string;
                }[];
                title?: {
                  [k: string]: unknown;
                }[];
                media?: {
                  ref?: string | Media;
                  maxHeight?: string;
                  aspectRatio?: string;
                  autoplay?: boolean;
                };
                mediaSticksToBottom?: boolean;
                grid?: boolean;
                actions?: {
                  action?: {
                    type?:
                      | 'reference'
                      | 'custom'
                      | 'current-document'
                      | 'app-store'
                      | 'google-play-store';
                    reference?: {
                      value?: {
                        value: string | Page;
                        relationTo: 'pages';
                      };
                    };
                    section?: string;
                    label?: string;
                    url?: string;
                    newTab?: boolean;
                    showArrow?: boolean;
                    params?: {
                      key: string;
                      value: string;
                      id?: string;
                    }[];
                    decoration?: {
                      variant?: 'text' | 'contained' | 'outlined';
                      color?: 'inherit' | 'primary' | 'secondary' | 'white';
                    };
                  };
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'features-block';
              }
            | {
                size?: 'default' | 'full-width';
                media: {
                  ref: string | Media;
                  maxHeight?: string;
                  aspectRatio?: string;
                  autoplay?: boolean;
                };
                bannerMedia: string | Media;
                caption?: string;
                centered?: boolean;
                id?: string;
                blockName?: string;
                blockType: 'media-block';
              }
            | {
                arrangement?: 'media-first' | 'content-first';
                emphasis?: 'moderate' | 'media' | 'content';
                content?: {
                  [k: string]: unknown;
                }[];
                showLicenceSnippet?: boolean;
                media: {
                  ref: string | Media;
                  maxHeight?: string;
                  aspectRatio?: string;
                  autoplay?: boolean;
                };
                bannerMedia: string | Media;
                mediaSticksToBottom?: boolean;
                actions?: {
                  action?: {
                    type?:
                      | 'reference'
                      | 'custom'
                      | 'current-document'
                      | 'app-store'
                      | 'google-play-store';
                    reference?: {
                      value?: {
                        value: string | Page;
                        relationTo: 'pages';
                      };
                    };
                    section?: string;
                    label?: string;
                    url?: string;
                    newTab?: boolean;
                    showArrow?: boolean;
                    params?: {
                      key: string;
                      value: string;
                      id?: string;
                    }[];
                    decoration?: {
                      variant?: 'text' | 'contained' | 'outlined';
                      color?: 'inherit' | 'primary' | 'secondary' | 'white';
                    };
                  };
                  id?: string;
                }[];
                hero?: boolean;
                id?: string;
                blockName?: string;
                blockType: 'media-content-block';
              }
            | {
                items?: {
                  icon?: {
                    ref?: string | Media;
                    maxHeight?: string;
                    aspectRatio?: string;
                    autoplay?: boolean;
                  };
                  content?: {
                    [k: string]: unknown;
                  }[];
                  centered?: boolean;
                  action?: {
                    enabled?: boolean;
                    value?: {
                      type?:
                        | 'reference'
                        | 'custom'
                        | 'current-document'
                        | 'app-store'
                        | 'google-play-store';
                      reference?: {
                        value?: {
                          value: string | Page;
                          relationTo: 'pages';
                        };
                      };
                      section?: string;
                      url?: string;
                      newTab?: boolean;
                      showArrow?: boolean;
                      params?: {
                        key: string;
                        value: string;
                        id?: string;
                      }[];
                      decoration?: {
                        variant?: 'text' | 'contained' | 'outlined';
                        color?: 'inherit' | 'primary' | 'secondary' | 'white';
                      };
                    };
                  };
                  id?: string;
                }[];
                columns?: string;
                mediaAspectRatio?: string;
                id?: string;
                blockName?: string;
                blockType: 'item-grid-block';
              }
            | {
                reference: string | ReusableContent;
                id?: string;
                blockName?: string;
                blockType: 'reusable-content-block';
              }
            | {
                tabs?: {
                  action?: {
                    type?:
                      | 'reference'
                      | 'custom'
                      | 'current-document'
                      | 'app-store'
                      | 'google-play-store';
                    reference?: {
                      value?: {
                        value: string | Page;
                        relationTo: 'pages';
                      };
                    };
                    section?: string;
                    label?: string;
                    url?: string;
                    newTab?: boolean;
                    showArrow?: boolean;
                    params?: {
                      key: string;
                      value: string;
                      id?: string;
                    }[];
                    decoration?: {
                      variant?: 'text' | 'contained' | 'outlined';
                      color?: 'inherit' | 'primary' | 'secondary' | 'white';
                    };
                  };
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'tabs-block';
              }
          )[];
          id?: string;
          blockName?: string;
          blockType: 'conditional-block';
        }
      | {
          content?: {
            [k: string]: unknown;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'content-block';
        }
      | {
          info?: {
            title?: {
              [k: string]: unknown;
            }[];
            items?: {
              icon?: {
                ref?: string | Media;
                maxHeight?: string;
                aspectRatio?: string;
                autoplay?: boolean;
              };
              content?: {
                [k: string]: unknown;
              }[];
              id?: string;
            }[];
            background?: {
              color?: string;
              pattern?:
                | 'none'
                | 'discs'
                | 'flat-discs'
                | 'left-positioned-logo'
                | 'right-positioned-logo'
                | 'spiral'
                | 'spiral-cluster';
              media?: {
                enabled?: boolean;
                value?: string | Media;
              };
            };
          };
          form?: {
            heading?: {
              [k: string]: unknown;
            }[];
            ref: string | Form;
          };
          id?: string;
          blockName?: string;
          blockType: 'form-with-info-block';
        }
      | {
          cards: {
            title?: string;
            content?: {
              [k: string]: unknown;
            }[];
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'expandable-cards-block';
        }
      | {
          compact?: boolean;
          columns: {
            sizeRatio: string;
            entries?: (
              | {
                  sizeRatio: string;
                  medias: {
                    gridMedia?: {
                      sizeRatio: string;
                      media?: string | Media;
                    };
                    id?: string;
                  }[];
                  id?: string;
                  blockName?: string;
                  blockType: 'row';
                }
              | {
                  gridMedia?: {
                    sizeRatio: string;
                    media?: string | Media;
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'media';
                }
            )[];
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'media-grid-block';
        }
      | {
          medias?: {
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            id?: string;
          }[];
          gap?: string;
          id?: string;
          blockName?: string;
          blockType: 'media-set-block';
        }
      | {
          actions?: {
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'action-group-block';
        }
      | {
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'testimonials-block';
        }
      | {
          type: 'coin-chronicles' | 'bankly-bytes';
          fixed?: boolean;
          postCount?: string;
          columns?: string;
          showCategoriesFilterBox?: boolean;
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'blog-posts-block';
        }
      | {
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'openings-block';
        }
      | {
          title?: {
            [k: string]: unknown;
          }[];
          assets?: {
            asset: string | Media;
            name?: string;
            boxed?: boolean;
            id?: string;
          }[];
          columns?: string;
          mediaAspectRatio?: string;
          hideDownloadButton?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'downloadable-assets-block';
        }
      | {
          cards?: {
            media?: {
              ref?: string | Media;
              maxHeight?: string;
              aspectRatio?: string;
              autoplay?: boolean;
            };
            label?: string;
            color?: string;
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'media-kit-cards-block';
        }
      | {
          latest?: boolean;
          configuration?: {
            title?: string;
            action?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
            postCount?: string;
          };
          columns?: string;
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'press-posts-block';
        }
      | {
          columns?: string;
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'team-members-block';
        }
      | {
          columns?: string;
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'case-studies-block';
        }
      | {
          columns?: string;
          populatedData?: {};
          populatable?: boolean;
          id?: string;
          blockName?: string;
          blockType: 'help-topics-block';
        }
      | {
          placeholder?: string;
          id?: string;
          blockName?: string;
          blockType: 'help-search-box-block';
        }
    )[];
    spacing?: {
      top?: boolean;
      bottom?: boolean;
    };
    background?: {
      color?: string;
      pattern?:
        | 'none'
        | 'discs'
        | 'flat-discs'
        | 'left-positioned-logo'
        | 'right-positioned-logo'
        | 'spiral'
        | 'spiral-cluster';
      media?: {
        enabled?: boolean;
        value?: string | Media;
      };
    };
    id?: string;
  }[];
  slug?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Header {
  id: string;
  name: string;
  definition?: {
    logo?: string | Media;
    items?: {
      hasChildren?: boolean;
      label?: string;
      action?: {
        type?:
          | 'reference'
          | 'custom'
          | 'current-document'
          | 'app-store'
          | 'google-play-store';
        reference?: {
          value?: {
            value: string | Page;
            relationTo: 'pages';
          };
        };
        section?: string;
        url?: string;
        newTab?: boolean;
        showArrow?: boolean;
        params?: {
          key: string;
          value: string;
          id?: string;
        }[];
        decoration?: {
          variant?: 'text' | 'contained' | 'outlined';
          color?: 'inherit' | 'primary' | 'secondary' | 'white';
        };
      };
      items: {
        content?: {
          [k: string]: unknown;
        }[];
        icon: {
          ref: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        action?: {
          type?:
            | 'reference'
            | 'custom'
            | 'current-document'
            | 'app-store'
            | 'google-play-store';
          reference?: {
            value?: {
              value: string | Page;
              relationTo: 'pages';
            };
          };
          section?: string;
          url?: string;
          newTab?: boolean;
          showArrow?: boolean;
          params?: {
            key: string;
            value: string;
            id?: string;
          }[];
          decoration?: {
            variant?: 'text' | 'contained' | 'outlined';
            color?: 'inherit' | 'primary' | 'secondary' | 'white';
          };
        };
        id?: string;
      }[];
      supportingContent?: {
        [k: string]: unknown;
      }[];
      id?: string;
    }[];
  };
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  alt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
export interface Footer {
  id: string;
  name: string;
  definition?: {
    sections: {
      title?: string;
      items?: {
        type?: 'link' | 'text';
        text?: string;
        action?: {
          type?:
            | 'reference'
            | 'custom'
            | 'current-document'
            | 'app-store'
            | 'google-play-store';
          reference?: {
            value?: {
              value: string | Page;
              relationTo: 'pages';
            };
          };
          section?: string;
          label?: string;
          url?: string;
          newTab?: boolean;
          showArrow?: boolean;
          params?: {
            key: string;
            value: string;
            id?: string;
          }[];
          decoration?: {
            variant?: 'text' | 'contained' | 'outlined';
            color?: 'inherit' | 'primary' | 'secondary' | 'white';
          };
        };
        id?: string;
      }[];
      id?: string;
    }[];
    additionalContent?: {
      [k: string]: unknown;
    }[];
    copyright?: string;
    legal?: {
      terms?: {
        type?:
          | 'reference'
          | 'custom'
          | 'current-document'
          | 'app-store'
          | 'google-play-store';
        reference?: {
          value?: {
            value: string | Page;
            relationTo: 'pages';
          };
        };
        section?: string;
        label?: string;
        url?: string;
        newTab?: boolean;
        showArrow?: boolean;
        params?: {
          key: string;
          value: string;
          id?: string;
        }[];
        decoration?: {
          variant?: 'text' | 'contained' | 'outlined';
          color?: 'inherit' | 'primary' | 'secondary' | 'white';
        };
      };
      'privacy-policy'?: {
        type?:
          | 'reference'
          | 'custom'
          | 'current-document'
          | 'app-store'
          | 'google-play-store';
        reference?: {
          value?: {
            value: string | Page;
            relationTo: 'pages';
          };
        };
        section?: string;
        label?: string;
        url?: string;
        newTab?: boolean;
        showArrow?: boolean;
        params?: {
          key: string;
          value: string;
          id?: string;
        }[];
        decoration?: {
          variant?: 'text' | 'contained' | 'outlined';
          color?: 'inherit' | 'primary' | 'secondary' | 'white';
        };
      };
    };
    background?: {
      color?: string;
      pattern?:
        | 'none'
        | 'discs'
        | 'flat-discs'
        | 'left-positioned-logo'
        | 'right-positioned-logo'
        | 'spiral'
        | 'spiral-cluster';
      media?: {
        enabled?: boolean;
        value?: string | Media;
      };
    };
  };
  createdAt: string;
  updatedAt: string;
}
export interface ReusableContent {
  id: string;
  name: string;
  definitions: (
    | {
        showBreadcrumb?: boolean;
        title: {
          [k: string]: unknown;
        }[];
        centered?: boolean;
        action?: {
          enabled?: boolean;
          value?: {
            type?:
              | 'reference'
              | 'custom'
              | 'current-document'
              | 'app-store'
              | 'google-play-store';
            reference?: {
              value?: {
                value: string | Page;
                relationTo: 'pages';
              };
            };
            section?: string;
            label?: string;
            url?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
        };
        expanded?: boolean;
        hero?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'title-block';
      }
    | {
        arrangement?: 'media-first' | 'content-first';
        emphasis?: 'moderate' | 'media' | 'content';
        content?: {
          [k: string]: unknown;
        }[];
        showLicenceSnippet?: boolean;
        media: {
          ref: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        bannerMedia: string | Media;
        mediaSticksToBottom?: boolean;
        actions?: {
          action?: {
            type?:
              | 'reference'
              | 'custom'
              | 'current-document'
              | 'app-store'
              | 'google-play-store';
            reference?: {
              value?: {
                value: string | Page;
                relationTo: 'pages';
              };
            };
            section?: string;
            label?: string;
            url?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        hero?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'media-content-block';
      }
    | {
        size?: 'default' | 'full-width';
        media: {
          ref: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        bannerMedia: string | Media;
        caption?: string;
        centered?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'media-block';
      }
    | {
        items?: {
          icon?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          content?: {
            [k: string]: unknown;
          }[];
          centered?: boolean;
          action?: {
            enabled?: boolean;
            value?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
          };
          id?: string;
        }[];
        columns?: string;
        mediaAspectRatio?: string;
        id?: string;
        blockName?: string;
        blockType: 'item-grid-block';
      }
    | {
        type?: 'default' | 'collapsible' | 'interactive';
        arrangement?: 'media-first' | 'content-first';
        features?: {
          content?: {
            [k: string]: unknown;
          }[];
          numbered?: boolean;
          icon?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          action?: {
            enabled?: boolean;
            value?: {
              type?:
                | 'reference'
                | 'custom'
                | 'current-document'
                | 'app-store'
                | 'google-play-store';
              reference?: {
                value?: {
                  value: string | Page;
                  relationTo: 'pages';
                };
              };
              section?: string;
              label?: string;
              url?: string;
              newTab?: boolean;
              showArrow?: boolean;
              params?: {
                key: string;
                value: string;
                id?: string;
              }[];
              decoration?: {
                variant?: 'text' | 'contained' | 'outlined';
                color?: 'inherit' | 'primary' | 'secondary' | 'white';
              };
            };
          };
          id?: string;
        }[];
        collapsibleFeatures?: {
          title?: string;
          content?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        interactiveFeatures?: {
          content?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        title?: {
          [k: string]: unknown;
        }[];
        media?: {
          ref?: string | Media;
          maxHeight?: string;
          aspectRatio?: string;
          autoplay?: boolean;
        };
        mediaSticksToBottom?: boolean;
        grid?: boolean;
        actions?: {
          action?: {
            type?:
              | 'reference'
              | 'custom'
              | 'current-document'
              | 'app-store'
              | 'google-play-store';
            reference?: {
              value?: {
                value: string | Page;
                relationTo: 'pages';
              };
            };
            section?: string;
            label?: string;
            url?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'features-block';
      }
    | {
        type: 'media' | 'agent';
        showArrows?: boolean;
        medias: {
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          label?: {
            [k: string]: unknown;
          }[];
          id?: string;
        }[];
        agents: string[] | Agent[];
        id?: string;
        blockName?: string;
        blockType: 'slider-block';
      }
    | {
        populatedData?: {};
        populatable?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'testimonials-block';
      }
    | {
        cards: {
          title?: string;
          content?: {
            [k: string]: unknown;
          }[];
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'expandable-cards-block';
      }
    | {
        compact?: boolean;
        columns: {
          sizeRatio: string;
          entries?: (
            | {
                sizeRatio: string;
                medias: {
                  gridMedia?: {
                    sizeRatio: string;
                    media?: string | Media;
                  };
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'row';
              }
            | {
                gridMedia?: {
                  sizeRatio: string;
                  media?: string | Media;
                };
                id?: string;
                blockName?: string;
                blockType: 'media';
              }
          )[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media-grid-block';
      }
    | {
        content?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content-block';
      }
    | {
        medias?: {
          media?: {
            ref?: string | Media;
            maxHeight?: string;
            aspectRatio?: string;
            autoplay?: boolean;
          };
          id?: string;
        }[];
        gap?: string;
        id?: string;
        blockName?: string;
        blockType: 'media-set-block';
      }
    | {
        actions?: {
          action?: {
            type?:
              | 'reference'
              | 'custom'
              | 'current-document'
              | 'app-store'
              | 'google-play-store';
            reference?: {
              value?: {
                value: string | Page;
                relationTo: 'pages';
              };
            };
            section?: string;
            label?: string;
            url?: string;
            newTab?: boolean;
            showArrow?: boolean;
            params?: {
              key: string;
              value: string;
              id?: string;
            }[];
            decoration?: {
              variant?: 'text' | 'contained' | 'outlined';
              color?: 'inherit' | 'primary' | 'secondary' | 'white';
            };
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'action-group-block';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
export interface Agent {
  id: string;
  name?: string;
  location?: string;
  photo?: string | Media;
  story?: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Form {
  id: string;
  title: string;
  fields?: (
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'text';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'textarea';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        options?: {
          label: string;
          value: string;
          id?: string;
        }[];
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'select';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'email';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'state';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'country';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'number';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        defaultValue?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'checkbox';
      }
    | {
        message?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'message';
      }
  )[];
  submitButtonLabel?: string;
  confirmationType?: 'message' | 'redirect';
  confirmationMessage: {
    [k: string]: unknown;
  }[];
  redirect?: {
    url: string;
  };
  emails?: {
    emailTo?: string;
    cc?: string;
    bcc?: string;
    replyTo?: string;
    emailFrom?: string;
    subject: string;
    message?: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
  slug?: string;
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  name?: string;
  role?: string | UserRole;
  photo?: string | Media;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface UserRole {
  id: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}
export interface Testimonial {
  id: string;
  name: string;
  rating: string;
  photo?: string | Media;
  content: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface CaseStudy {
  id: string;
  pageLayout?: {
    header: string | Header;
    footer: string | Footer;
  };
  name: string;
  media?: string | Media;
  content: {
    [k: string]: unknown;
  }[];
  slug?: string;
  createdAt: string;
  updatedAt: string;
}
export interface Opening {
  id: string;
  pageLayout?: {
    header: string | Header;
    footer: string | Footer;
  };
  title?: string;
  department?: string;
  location?: string;
  remote?: boolean;
  description?: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface BlogPost {
  id: string;
  pageLayout?: {
    header: string | Header;
    footer: string | Footer;
  };
  type: 'coin-chronicles' | 'bankly-bytes';
  title: string;
  summary: string;
  author: string | User;
  category: string | BlogPostCategory;
  slug?: string;
  media?: {
    ref?: string | Media;
    maxHeight?: string;
    aspectRatio?: string;
    autoplay?: boolean;
  };
  tags?: string;
  estimatedReadTime: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface BlogPostCategory {
  id: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}
export interface HelpTopic {
  id: string;
  pageLayout?: {
    header: string | Header;
    footer: string | Footer;
  };
  icon: string | Media;
  title: string;
  slug?: string;
  handler?: string | User;
  description?: {
    [k: string]: unknown;
  }[];
  meta?: {
    answerCount?: string;
    helpfulCount?: string;
    unhelpfulCount?: string;
    viewCount?: string;
  };
  createdAt: string;
  updatedAt: string;
}
export interface HelpArticle {
  id: string;
  pageLayout?: {
    header: string | Header;
    footer: string | Footer;
  };
  topic?: string | HelpTopic;
  title: string;
  slug?: string;
  summary?: string;
  author?: string | User;
  content?: {
    [k: string]: unknown;
  }[];
  meta?: {
    helpfulCount?: string;
    unhelpfulCount?: string;
    viewCount?: string;
  };
  createdAt: string;
  updatedAt: string;
}
export interface TeamMember {
  id: string;
  name?: string;
  designation?: string;
  media?: string | Media;
  createdAt: string;
  updatedAt: string;
}
export interface PressPost {
  id: string;
  title: string;
  description: string;
  media: string | Media;
  url: string;
  date?: string;
  createdAt: string;
  updatedAt: string;
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?: {
    field: string;
    value: string;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
